# Generated by Django 5.2.7 on 2025-12-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_force_password_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee')], db_index=True, default='Employee', help_text='User role', max_length=20),
        ),
    ]
